### ISSUE TITLE
Define message body exchanged between server and client

### ISSUE THREAD

**Issue by hfreire** [feedeo/feedeo-wonderwall#2]

**Comment by hfreire** [comment]
Consider sending URL of image instead of blob through RabbitMQ.

**Comment by fredrikholmen** [comment]
Message body proposal - JSON object 
```javascript
{ 
    url: <image url>, 
    query: <text> 
}
```

I never considered the blob

**Comment by hfreire** [comment]
Changes to your proposal

```json
{
  "url": "https://pbs.twimg.com/profile_images/632130141397774337/gY4orlTb.png",
  "timeout": 10
}
```

`url` is required
`timeout` is optional. You can override the image display duration. The unit is in seconds. The default value is 10 seconds.

`query` what should we do with this?
