### ISSUE TITLE
Expose server configuration through environment variables

### ISSUE THREAD

**Issue by hfreire** [feedeo/feedeo-wonderwall#6]
...so it plays nice with the docker container.

**Comment by fredrikholmen** [comment]
ok, I hear you.

//F
________________________________________________________________________________________
Fredrik Holmén, CEO Keybroker Group
fredrik.holmen@keybroker.com | @fredrikh | +46 734 332 501

!!! We have a new office - Welcome to Sveavägen 63, 113 50 Stockholm, Sweden

**Comment by hfreire** [comment]
Fixed.
